[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.3",
    "kubernetes>=31.0.0",
    "requests>=2.32.3",
    "trafilatura>=1.12.2",
]
