// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/19/2024, 2:58:00 AM
const configMerger = require("/home/runner/workspace/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/runner/workspace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/plugins/**/*.{js,ts,mjs}","/home/runner/workspace/frontend/composables/**/*.{js,ts,mjs}","/home/runner/workspace/frontend/utils/**/*.{js,ts,mjs}","/home/runner/workspace/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/runner/workspace/frontend/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["17"] = "/home/runner/workspace/frontend/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
